% DESCRIPTION:
% Script executing everything in the right order.

%% Initialization (generate various initial states)
init_for_DC_grid

%%
clear all
close all
clc

%% Set the reward strategy
makeRewardCurveSOC
makeRewardCurvePFC

%% Initialize the parameters for learning session:
simulation_parameters_1 = struct(...
    'model','DC_grid_V2',...
    'maxEpi',2,...
    'totalTime',20,...
    'iterationTime',1.3,...
    'learnRate',0.99,...
    'epsilon',0.5,...
    'epsilonDecay',0.9996,...
    'discount',0.9,...
    'successRate',1,...
    'rewardCurveSOC','rewardCurveSOC.mat',...
    'rewardCurvePFC','rewardCurvePFC.mat',...
    'subFolder','test_PFC'...
    );

%% Run Machine Learning
global inputsFromWS
directory = '14_july';
QlearningEMS(simulation_parameters_1,directory);
